{{- if .Values.imageRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageRegistry.server .Values.imageRegistry.username .Values.imageRegistry.password (printf "%s:%s" .Values.imageRegistry.username .Values.imageRegistry.password | b64enc) | b64enc }}
{{- end }}
