kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-monitor
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-monitor
    spec:
      {{- if .Values.imageRegistry.enabled }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry-secret
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-monitor
          image: {{ .Values.monitor.image }}
          env:
            - name: RESINC_TIME
              value: "{{ printf "%v" .Values.monitor.resyncTime }}"
            - name: CONTROLLER_WORKERS
              value: "{{ printf "%v" .Values.monitor.workers }}"
            - name: user
              value: {{ .Values.postgresql.username }}
            - name: password
              value: {{ .Values.postgresql.password }}
            - name: database
              value: {{ .Values.postgresql.name }}
            - name: host
              value: {{ .Release.Name }}-postgres-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: port
              value: "{{ printf "%v" .Values.postgresql.port }}"
            - name: PROMETHEUS_SERVER
              value: "{{ .Values.prometheus.prometheusServerAddress }}"
            - name: price_uri
              value: "http://{{ .Release.Name }}-price.{{ .Release.Namespace }}.svc.cluster.local"
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: klustercost
      serviceAccount: klustercost
      securityContext: {}
      schedulerName: default-scheduler